//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShoppingCart.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eShoppingDBEntities : DbContext
    {
        public eShoppingDBEntities()
            : base("name=eShoppingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartM> CartMs { get; set; }
        public virtual DbSet<CartStatusM> CartStatusMs { get; set; }
        public virtual DbSet<CategoryM> CategoryMs { get; set; }
        public virtual DbSet<MemberRoleM> MemberRoleMs { get; set; }
        public virtual DbSet<MembersM> MembersMs { get; set; }
        public virtual DbSet<ProductM> ProductMs { get; set; }
        public virtual DbSet<RolesM> RolesMs { get; set; }
        public virtual DbSet<ShippigDetailsM> ShippigDetailsMs { get; set; }
        public virtual DbSet<SlideImageM> SlideImageMs { get; set; }
    
        public virtual ObjectResult<e_SearchByName_Result> e_SearchByName(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<e_SearchByName_Result>("e_SearchByName", searchParameter);
        }
    }
}
